FROM ubuntu:latest

WORKDIR /home

RUN apt update

RUN apt upgrade -y

#安装 wget

RUN apt install wget -y

#安装Mysql

RUN apt install mysql-server -y

#安装 .NetCore

RUN wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

RUN dpkg -i packages-microsoft-prod.deb

RUN rm packages-microsoft-prod.deb

RUN apt update

RUN apt install apt-transport-https -y

RUN apt update

RUN apt install aspnetcore-runtime-3.1 -y

#安装 Nginx

RUN apt install nginx -y

#复制项目